### ISSUE TITLE
arraycopy复制时ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by manhere** [handsomestWei/sl651-2014#5]
应为 #4 修复不完全所致

```
java.lang.ArrayIndexOutOfBoundsException: null
        at java.lang.System.arraycopy(Native Method) ~[na:1.8.0_402]
        at com.wjy.sl6512014.util.FrameUtil.getM124Body(FrameUtil.java:99) ~[classes!/:0.0.1]
```

**Comment by handsomestWei** [comment]
没有吧^_^配置文件设置```header_delimiter_flag=true```开启包分割，在[client包](https://github.com/handsomestWei/sl651-2014/tree/main/src/main/java/com/wjy/sl6512014/client)里模拟发送试试

**Comment by ym6009** [comment]
没有处理扩展字段的原因
